/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CButton: typeof import('./src/components/common/CButton.vue')['default']
    DebugInfo: typeof import('./src/components/DebugInfo.vue')['default']
    IconAuto: typeof import('./src/components/Icon/IconAuto.vue')['default']
    IconClose: typeof import('./src/components/Icon/IconClose.vue')['default']
    IconDownload: typeof import('./src/components/Icon/IconDownload.vue')['default']
    IconExpand: typeof import('./src/components/Icon/IconExpand.vue')['default']
    IconFunnelSolid: typeof import('./src/components/Icon/IconFunnelSolid.vue')['default']
    IconGithub: typeof import('./src/components/Icon/IconGithub.vue')['default']
    IconInfo: typeof import('./src/components/Icon/IconInfo.vue')['default']
    IconLeft: typeof import('./src/components/Icon/IconLeft.vue')['default']
    IconLoading: typeof import('./src/components/Icon/IconLoading.vue')['default']
    IconMenu: typeof import('./src/components/Icon/IconMenu.vue')['default']
    IconMoon: typeof import('./src/components/Icon/IconMoon.vue')['default']
    IconOpen: typeof import('./src/components/Icon/IconOpen.vue')['default']
    IconRight: typeof import('./src/components/Icon/IconRight.vue')['default']
    IconSearch: typeof import('./src/components/Icon/IconSearch.vue')['default']
    IconShrink: typeof import('./src/components/Icon/IconShrink.vue')['default']
    IconStack: typeof import('./src/components/Icon/IconStack.vue')['default']
    IconSun: typeof import('./src/components/Icon/IconSun.vue')['default']
    IconTablet: typeof import('./src/components/Icon/IconTablet.vue')['default']
    IconTag: typeof import('./src/components/Icon/IconTag.vue')['default']
    IconTitle: typeof import('./src/components/Icon/IconTitle.vue')['default']
    IconUser: typeof import('./src/components/Icon/IconUser.vue')['default']
    ImageInfo: typeof import('./src/components/ImageInfo.vue')['default']
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    MasonryItem: typeof import('./src/components/Masonry/MasonryItem.vue')['default']
    MasonryView: typeof import('./src/components/Masonry/MasonryView.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar/Sidebar.vue')['default']
    SidebarBlock: typeof import('./src/components/Sidebar/SidebarBlock.vue')['default']
    SidebarHead: typeof import('./src/components/Sidebar/SidebarHead.vue')['default']
    SidebarMask: typeof import('./src/components/Sidebar/SidebarMask.vue')['default']
    Switch: typeof import('./src/components/common/Switch.vue')['default']
    TextBox: typeof import('./src/components/common/TextBox.vue')['default']
    Tip: typeof import('./src/components/Tip.vue')['default']
  }
}
